version: "3"
services:
  mysql:
    image: mysql
    environment:
      MYSQL_DATABASE: obab
      MYSQL_ROOT_PASSWORD: 1234
      MYSQL_ROOT_HOST: '%'
    ports:
      - 3306:3306

  redis:
    image: redis
    ports:
      - 6379:6379


