spring:
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  redis:
    host: 3.37.236.75
    port: 6379
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://3.37.236.75:3306/obab
    username: obab
    password: 1234
  jpa:
    database: mysql
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    generate-ddl: true
    hibernate:
      ddl-auto: none
fcm:
  project-id: "obab-1fbb7"
  firebase-path: "firebase/obab-1fbb7-firebase-adminsdk-zl94u-069a3352bf.json"
